# Spacy is a library in python which specicilaise in the NLP tasks doing named entity recognition 

# What spacy does ?

# 1. Tokenization
# 2. Part of speech recognition ( labelling words as noun, verb)
# 3. Named entity recognition ( Identifies people, places, dates etc)
# 4. Dependency parsing (find subject verb object relationship)
# 5. lemmatization ( get base form of word )

# Altenrnative are transformers and nltk

# It will create subject, object , predicate ( predicate is kind of relationship between subject and object)

import spacy 
import json


nlp = spacy.load("en_core_web_sm")


# en_core_web_sm is spaCy’s small English language model

def extract_triplets(text):

    doc = nlp(text)
    triples = []

    for sentence in doc.sents:

        parsed_text = nlp(sentence.text)
        subj, rel, obj = None, None, None

        for token in parsed_text:

            # print(json.dumps(token))
            # print("token -- ", token , "\n \n \n")

            if "subj" in token.dep_:
                subj = token.text
            elif "obj" in token.dep_:
                obj = token.text
            elif token.pos_=="VERB":
                rel = token.lemma_
        
        if subj and rel and obj :
            triples.append((subj, rel, obj))

    return triples

# Generated triplets

#  - (that, stretch, years)
#  - (that, rule, Sultanate)
#  - (mass, stretch, Nepal)
#  - (Sultanate, have, culture)
#  - (it, enquire, Prelims)
#  - (era, capture, AD)
#  - (rule, change, invasion)
#  - (Ghori, expand, subcontinent)
#  - (He, fight, Tarain)
#  - (he, lose, ruler)
#  - (he, defeat, Chauhan)
#  - (which, outnumber, army)
#  - (Ghori, establish, India)
#  - (which, mark, Sultanate)
#  - (which, list, table)
#  - (dynasty, belong, race)
#  - (dynasty, have, Sultans)
#  - (It, reign, AD)
#  - (Relation, list, Qutb)
#  - (dynasty, rule, c.)
#  - (that, establish, period)
#  - (himself, declare, 1192)
#  - (dynasty, know, dynasty)
#  - (Mumluk, enslave, person)
#  - (Aibak, found, dynasty)
#  - (he, play, Tarain)
#  - (him, make, possessions)
#  - (He, know, generosity)
#  - (He, din, Ajmer)
#  - (He, construct, Minar)
#  - (he, play, chaugan)
#  - (son, remove, throne)
#  - (he, declare, ruler)
#  - (He, make, months)
#  - (Itutmish, consider, India)
#  - (dynasty, make, tribe)
#  - (him, marry, him)
#  - (He, appoint, Aibek)
#  - (Iltutmish, take, Shamsuddin)
#  - (He, regard, India)
#  - (Khan, start, Asia)
#  - (He, defeat, Khwarizm)
#  - (Mangabarni, seek, Iltutmish)
#  - (Iltutmish, save, onslaught)
#  - (family, progress, land)
#  - (He, shift, Lahore)
#  - (which, make, India)
#  - (He, complete, India)
#  - (He, introduce, India)
#  - (tanka, become, India)
#  - (tanka, become, rupee)
#  - (He, come, reign)
#  - (that, grace, halls)
#  - (that, bring, Ghori)
#  - (that, make, collection)
#  - (He, nominate, successor)
#  - (He, reign, AD)
#  - (Iltutmish, name, line)
#  - (woman, hold, Sultan)
#  - (who, ascend, throne)
#  - (Shah, suppress, revolt)
#  - (that, belong, her)
#  - (Sultan, rule, Delhi)
#  - (she, appoint, head)
#  - (Yakut, murder, which)
#  - (Sultan, kill, Iltutmish)
#  - (She, reign, AD)
#  - (fall, pave, Forty)
#  - (reign, continue, Sultan)
#  - (nobles, support, Shah)
#  - (Shah, kill, army)
#  - (he, choose, ruler)
#  - (he, replace, Mahmud)
#  - (Nasiruddin, ascend, throne)
#  - (he, face, court)
#  - (Balban, ascend, throne)
#  - (he, have, ruling)
#  - (Balban, kill, family)
#  - (him, understand, problems)
#  - (He, call, threat)
#  - (it, become, Sultan)
#  - (He, separate, department)
#  - (He, reorganise, army)
#  - (which, translate, God)
#  - (Balban, enhance, monarchy)
#  - (nobles, highlight, him)
#  - (He, start, Navroz)
#  - (reign, see, invasion)
#  - (he, safeguard, invasion)
#  - (He, reign, AD)
#  - (Kaiqubad, make, nobles)
#  - (He, replace, son)
#  - (Ariz, capture, throne)
#  - (He, establish, dynasty)
#  - (dynasty, belong, race)
#  - (Rulers, din, Khalji)
#  - (Khalji, din, dynasty)
#  - (he, come, power)
#  - (He, fight, Mongols)
#  - (Khaljis, •, descent)
#  - (they, dismiss, officials)
#  - (rise, mark, monopoly)
#  - (He, soften, rule)
#  - (who, deny, population)
#  - (state, base, people)
#  - (He, avoid, tolerance)
#  - (he, murder, law)
#  - (Khalji, know, India)
#  - (Khilji, pay, cash)
#  - (He, know, Darwaja)
#  - (He, collect, cash)
#  - (which, •, tolerance)
#  - (that, increase, liquor)
#  - (sale, prohibit, liquor)
#  - (nobles, reorganise, purview)
#  - (activities, report, Sultan)
#  - (gatherings, allow, Sultan)
#  - (Campaigns, have, experience)
#  - (it, have, reign)
#  - (he, stand, army)
#  - (He, stop, invasions)
#  - (Malik, protect, frontier)
#  - (Some, list, reference)
#  - (army, win, 1299)
#  - (queen, send, Delhi)
#  - (person, send, Delhi)
#  - (Khalji, have, time)
#  - (fort, fall, Alauddin)
#  - (women, commit, immolation)
#  - (Chittor, fall, 1303)
#  - (motivation, attack, Singh)
#  - (women, perform, Jauhar)
#  - (episode, write, Jayasi)
#  - (army, capture, 1305)
#  - (Khalji, capture, Rajputana)
#  - (Yadavas, rule, region)
#  - (Kafur, lead, Alauddin)
#  - (Malik, honour, him)
#  - (Khalji, patronize, Hasan)
#  - (He, know, Darwaza)
#  - (He, construct, Siri)
#  - (Alauddin, call, Hind)
#  - (he, keep, empire)
#  - (Khalji, recruit, cavalrymen)
#  - (which, prepare, soldiers)
#  - (market, dry, commodities)
#  - (who, preside, markets)
#  - (supply, maintain, storehouses)
#  - (Regulations, fix, commodities)
#  - (Riyasat, call, officer)
#  - (Munhiyans, detail, markets)
#  - (He, check, prices)
#  - (Anyone, receive, punishment)
#  - (prices, remain, commodities)
#  - (land, measure, Delhi)
#  - (officer, fix, revenue)
#  - (revenue, accumulate, cash)
#  - (Sultan, pay, cash)
#  - (reforms, provide, future)
#  - (Shah, ascend, throne)
#  - (little, make, bid)
#  - (who, take, throne)
#  - (it, start, end)
#  - (Malik, kill, Shah)
#  - (He, ascend, Delhi)
#  - (dynasty, belong, race)
#  - (dynasty, conquer, areas)
#  - (dynasty, call, origin)
#  - (rulers, list, table)
#  - (I, know, Nusrat)
#  - (•, found, dynasty)
#  - (city, make, Tughlaqabad)
#  - (He, die, 1325)
#  - (elephant, fall, pavilion)
#  - (son, kill, him)
#  - (He, enlighten, sultans)
#  - (that, introduce, time)
#  - (He, control, India)
#  - (He, move, capital)
#  - (capital, rename, Daulatabad)
#  - (he, be, Daulatabad)
#  - (people, die, journey)
#  - (which, replace, coins)
#  - (who, issue, China)
#  - (people, exchange, ones)
#  - (which, induce, treasury)
#  - (which, empty, treasury)
#  - (Tughlaq, induce, rivers)
#  - (farmers, revolt, region)
#  - (steps, crush, revolt)
#  - (Reforms, set, cultivation)
#  - (division, handle, agriculture)
#  - (that, sprawl, miles)
#  - (step, continue, Tughlaq)
#  - (he, worsen, condition)
#  - (Tughlaq, accord, opposites)
#  - (death, mark, decline)
#  - (Tughlaq, choose, Tughlaq)
#  - (He, annex, south)
#  - (which, translate, language)
#  - (He, take, administration)
#  - (he, allow, properties)
#  - (which, make, system)
#  - (taxes, levy, teachings)
#  - (Jizya, collect, Muslims)
#  - (that, levy, them)
#  - (they, go, Islam)
#  - (he, serve, Lodi)
#  - (He, impose, tax)
#  - (He, build, canals)
#  - (that, generate, revenue)
#  - (that, run, manpower)
#  - (who, compose, Shah)
#  - (who, compose, Sulatin)
#  - (He, write, book)
#  - (struggle, begin, power)
#  - (Sultanate, break, provinces)
#  - (invasion, result, losses)
#  - (dynasty, crumble, which)
#  - (Dynasty, rule, succession)
#  - (Sayyids, follow, Mohammad)
#  - (successors, •, ruling)
#  - (It, attack, Dynasty)
#  - (He, reign, AD)
#  - (names, list, Lodi)
#  - (who, end, period)
#  - (He, found, dynasty)
#  - (he, annex, regions)
#  - (He, introduce, coins)
#  - (he, succeed, son)
#  - (He, take, Gulrukhi)
#  - (he, defeat, chiefs)
#  - (it, make, 1504)
#  - (he, know, Sikandar)
#  - (facilities, provide, peasantry)
#  - (He, torture, poet)
#  - (He, reimpose, Muslims)
#  - (Lodhi, rule, 1517)
#  - (Lodhi, succeed, AD)
#  - (which, create, Sultanate)
#  - (Babur, defeat, Panipat)
#  - (Sultanate, start, Mughals)